# ML-Workflow for the Titanic Survival Dataset

This script contains a short workflow to predict survival on the titanic using passenger information. It is divided into six steps, ranging from data preprocessing and feature engineering to hyperparameter search for logistic regression, XGClassifier and a random tree classifier.

The dataset can be found here: kaggle.com/competitions/titanic/data

## Step 1: Data inspection

In [1]:
# load libraries and set random seed
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
# models to be compared:
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

rs = 42  # random seed
np.random.seed(rs)

In [2]:
# Print file names in directory
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

In [3]:
# specify input paths
train_file_path = '/kaggle/input/titanic/train.csv'
test_file_path = '/kaggle/input/titanic/test.csv'

# load files as pandas dataframes
train_data = pd.read_csv(train_file_path)  
test_data = pd.read_csv(test_file_path)

In [4]:
# display the first fifteen entries
train_data.head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

In [5]:
# display dataframe info
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

A quick view of the data suggests the following:

- 'Cabin' has many missing values and non-null values are not on an ordinal scale. Therefore, recode 'Cabin' into binary.
- 'Ticket' mixes strings and numbers and is not on a true numeric or ordinal scale. Exclude variable from classification.
- 'Age' and 'Fare' are the only continuous variables. Including binned variants of these variables might help to capture non-linear dependencies.
- 'Name' contains the usual titles like 'Miss', but unsual title like 'Master' appear. Extract unique titles next and possibly create a new category for rare titles.
- The number of siblings and parents on board ('SibSp' and 'Parch') is expressed on an integer scale. Combining these into a single features might boost classification. Also, perhaps having no family on board is a special case and a binary variable could capture a non-linear trend here.

In [6]:
# extract title information from names
titles = train_data["Name"].str.extract(" ([A-Za-z]+)\\.", expand=False)
# show number of appearances of unique titles
titles.value_counts()

Name
Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Col           2
Mlle          2
Major         2
Ms            1
Mme           1
Don           1
Lady          1
Sir           1
Capt          1
Countess      1
Jonkheer      1
Name: count, dtype: int64

There are a number of  titles that appear quite infrequently compared to 'Mr' or 'Miss'. Recode those titles into a 'rare' category. Also, there appear to be some titles that probably should be recoded to the more common entries, such as 'Mlle' or 'Ms'.

## Step 2: Feature engineering

In [7]:
# define a function to add engineered features
def add_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    
    # Recode title categories
    df["Title"] = df["Name"].str.extract(" ([A-Za-z]+)\\.", expand=False)
    df['Title'] = df['Title'].replace(['Dr', 'Rev', 'Col', 'Major', 'Capt', 'Don', 'Lady', 'Sir', 'Countess', 'Jonkheer'], 'Rare') 
    df['Title'] = df['Title'].replace('Mlle', 'Miss')
    df['Title'] = df['Title'].replace('Ms', 'Miss')
    df['Title'] = df['Title'].replace('Mme', 'Mrs')
    
    # recode cabin
    df['IsCabin'] = df['Cabin'].isna().astype(int)

    # define a binned variable for age
    bins = [0, 5, 12, 18, 120]
    labels = ['0–5', '6-12', '13–18', '19+']
    df['AgeBin'] = pd.cut(df['Age'], bins=bins, labels=labels, right=False)

    # define a binned variable for fare
    bins = [0, 20, 40, 60, 100, 200, 700]
    labels = ['0–20', '21-40', '41–60', '61-100', '101-200', '201+']
    df['FareBin'] = pd.cut(df['Fare'], bins=bins, labels=labels, right=False)

    # include additional variables
    # rank fare within each class
    df['FareRankWithinClass'] = df['Fare'].groupby(df['Pclass']).rank()

    # Add novel family features
    df['FamilySize'] = df['SibSp'].fillna(0) + df['Parch'].fillna(0) + 1 # total number of family members
    df['IsAlone'] = (df['FamilySize'] == 1).astype(int) # passenger traveling with or without family

    return df

In [8]:
# add features to train and test data
train_data = add_features(train_data)
test_data = add_features(test_data)

## Step 3: Pipeline set-up

In [9]:
# choose features to process
numerical_features = ['Age', 'SibSp', 'FamilySize', 'Parch', 'FareRankWithinClass']
categorical_features = ['Pclass', 'Sex', 'Title', 'Embarked', 'AgeBin', 'FareBin'] #'Sex_Embarked', 'Sex_Pclass'
binary_features = ['IsAlone', 'IsCabin']

In [10]:
# preprocessing numerical features (insert median for missing values and use z-score scaling)
numerical_transformer = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy = 'median')),
    ('scaler', StandardScaler())
])

# preprocessing categorical features (insert most frequent for missing values)
categorical_transformer = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy = 'most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown = 'ignore'))
])

# preprocessing binary features (insert most frequent for missing values)
binary_transformer = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy = 'most_frequent'))
])

In [11]:
# define the columns transformer
preprocessor = ColumnTransformer(transformers = [
    ('num', numerical_transformer, numerical_features),
    ('cat', categorical_transformer, categorical_features),
    ('bin', binary_transformer, binary_features)
])

In [12]:
# prepare the train and test datasets
y = train_data.Survived
X = train_data[numerical_features + categorical_features + binary_features]
X_test = test_data[numerical_features + categorical_features + binary_features]

## Step 4: Logistic regression: Hyperparameter search + cross-validation

In this section, a grid search function is defined to make it easier to run different models with varying parameters. The results of the logistic regression can therefore later be compared against other models.

In [13]:
def run_grid_search(estimator, param_grid, preprocessor, X, y, cv, scoring="accuracy"):
    """
    Helper function to run grid searches with cross-validation for any classifiers
    
    - Parameters
    
    estimator: classifier to be used
    param_grid: dict of model-specific hyperparameters
    preprocessor: Preprocessing pipeline.
    X, y: Predictor and target variables
    cv: previously defined k-fold split for cross-validation
    scoring: scoring metric (str)
    
    - Returns
    
    grid_search: fitted grid search object
    results_df : DataFrame with parameters mean/std
    """
    # define pipeline
    pipe = Pipeline([
        ('preprocessor', preprocessor),
        ('model', estimator)
    ])

    # set-up grid search
    grid = GridSearchCV(
        estimator=pipe,
        param_grid=param_grid,
        cv=cv,
        scoring=scoring,
        return_train_score=True
    )

    # run grid search
    grid.fit(X, y)

    # Extract results across runs (this runs independent of how many parameters are specified)
    results_df = pd.DataFrame({
        key.replace("param_model__", ""): grid.cv_results_[key]
        for key in grid.cv_results_.keys()
        if key.startswith("param_model__")
    })
    
    results_df["mean_accuracy"] = grid.cv_results_["mean_test_score"]
    results_df["std_accuracy"] = grid.cv_results_["std_test_score"]

    return grid, results_df.sort_values("mean_accuracy", ascending=False)

In [14]:
# define splits for cross-validation
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=rs) # stratified folds help against imbalances in the target

# set values to test for the c-parameter
param_grid_lr = {
    'model__C': [0.05, 0.1, 0.2, 0.5, 1, 2, 3, 5, 10]
}

# define logistic regression
lr_estimator = LogisticRegression(
    max_iter=5000,
    penalty='l1', # important to use L1 so unnecessary features are set to zero
    solver='liblinear'
)

# run grid search
grid_lr, results_lr = run_grid_search(
    estimator=lr_estimator,
    param_grid=param_grid_lr,
    preprocessor=preprocessor,
    X=X,
    y=y,
    cv=kf
)

# show the results
results_lr

       C  mean_accuracy  std_accuracy
3   0.50       0.826031      0.010161
4   1.00       0.824914      0.009696
5   2.00       0.824907      0.012108
2   0.20       0.821555      0.011344
7   5.00       0.821543      0.012588
6   3.00       0.821543      0.012588
8  10.00       0.820419      0.012902
1   0.10       0.805857      0.021873
0   0.05       0.791269      0.015303

## Step 5: Comparison of different models (XGBoost and random tree models)

In [15]:
# set parameters to test for XGBoost
param_grid_xgb = {
    'model__max_depth': [2, 3, 4, 5],
    'model__learning_rate': [0.01, 0.05, 0.1]
}

# run grid search
xgb_estimator = XGBClassifier(
    random_state=rs,
    reg_alpha=0.1, # L1 regularization
    reg_lambda=1 # L2 regularization
)

grid_xgb, results_xgb = run_grid_search(
    estimator=xgb_estimator,
    param_grid=param_grid_xgb,
    preprocessor=preprocessor,
    X=X,
    y=y,
    cv=kf
)

results_xgb

    learning_rate  max_depth  mean_accuracy  std_accuracy
11           0.10          5       0.848465      0.019913
9            0.10          3       0.843977      0.020036
10           0.10          4       0.843977      0.019396
6            0.05          4       0.841730      0.023260
7            0.05          5       0.838359      0.018442
8            0.10          2       0.837248      0.015614
5            0.05          3       0.835001      0.019452
3            0.01          5       0.831624      0.015726
4            0.05          2       0.829396      0.011697
2            0.01          4       0.828253      0.020496
1            0.01          3       0.823784      0.016223
0            0.01          2       0.804714      0.018927

In [16]:
# set parameters to test for random forest classifier
param_grid_rf = {
    'model__n_estimators': [100, 150, 200],
    'model__max_depth': [3, 5, 7]
}

rf_estimator = RandomForestClassifier(random_state=rs)

grid_rf, results_rf = run_grid_search(
    estimator=rf_estimator,
    param_grid=param_grid_rf,
    preprocessor=preprocessor,
    X=X,
    y=y,
    cv=kf
)

results_rf

   max_depth  n_estimators  mean_accuracy  std_accuracy
3          5           100       0.836137      0.010918
6          7           100       0.832766      0.007571
7          7           150       0.832760      0.008477
4          5           150       0.831636      0.010849
5          5           200       0.830513      0.008523
8          7           200       0.828272      0.006990
0          3           100       0.823796      0.015285
1          3           150       0.822666      0.011075
2          3           200       0.822666      0.011075

All in all, the XGClassifier has a slight advantage over the logistic regression and random forest classifiers.

## Step 6: Model training + deployment

Next, the final models are run on the test dataset. Test accuracy is obtained after uploading the submission to kaggle.

In [17]:
# define the final model for logistic regression
best_c = results_lr['C'].iloc[0]

model = Pipeline(steps = [
    ('preprocessor', preprocessor),
    ('model', LogisticRegression(
        max_iter=5000,
        penalty='l1',
        solver='liblinear',
        C=best_c
    ))
])

# train the model and predict test data
model.fit(X,y)
y_pred = model.predict(X_test)

# create results dataframe
submission = pd.DataFrame({
    'PassengerId': test_data['PassengerId'],
    'Survived': y_pred
})

# save in .csv format
submission.to_csv("submission_lr.csv", index=False)

In [18]:
# define the final model for XGClassifier
best_max_depth = results_xgb['max_depth'].iloc[0]
best_learning_rate = results_xgb['learning_rate'].iloc[0]

model = Pipeline(steps = [
    ('preprocessor', preprocessor),
    ('model', XGBClassifier(
        random_state=rs,
        max_depth=best_max_depth,
        learning_rate=best_learning_rate
    ))
])

# train the model and predict test data
model.fit(X,y)
y_pred = model.predict(X_test)

# create results dataframe
submission = pd.DataFrame({
    'PassengerId': test_data['PassengerId'],
    'Survived': y_pred
})

# save in .csv format
submission.to_csv("submission_xg.csv", index=False)

In [19]:
# define the final model for random forest classifier
best_max_depth = results_rf['max_depth'].iloc[0]
best_n_estimator = results_rf['n_estimators'].iloc[0]

model = Pipeline(steps = [
    ('preprocessor', preprocessor),
    ('model', RandomForestClassifier(
        random_state=rs,
        max_depth=best_max_depth,
        n_estimators=best_n_estimator
    ))
])

# train the model and predict test data
model.fit(X,y)
y_pred = model.predict(X_test)

# create results dataframe
submission = pd.DataFrame({
    'PassengerId': test_data['PassengerId'],
    'Survived': y_pred
})

# save in .csv format
submission.to_csv("submission_rf.csv", index=False)

After hyperparameter tuning, both logistic regression and the random tree classifier achieved a test accuracy of ~78%. The XGClassifier remained at ~76% despite regularization, and showed a larger gap between cross-validated and test performance. This indicates that the model is likely overfitting to the small training set. The slightly better generalization of the simpler models is consistent with the limited dataset size, where lower-variance models often perform better.